### DISCUSSION TITLE
Help updating /etc/hosts and installing drivers

### DISCUSSION THREAD

**Discussion by mightymouse2045** [rancher/elemental#1393] [Q&A] [answered]
Hi,

I have updated my seedimage to add entries in /etc/hosts, but this doesn't carry across to the OS post install. I've tried updating it in the after-install-chroot stage which is also where I am trying to install RPM's https://elemental.docs.rancher.com/customizing#adding-extra-driver-binaries-into-the-iso-example 

But the commands I am running don't appear to do anything - after reboot there are no host entries and the rpm packages I have attempted to install are not there?

Not sure what I'm doing wrong? Can anyone help out with how they've done it? 

Also is there a way to get back into chroot manually - I have disabled the auto reboot/shutdown after the OS install, so wanted to manually go back into the chroot environment and see what has or hasn't been applied and troubleshoot it further that way.

**Comment by kkaempf** [comment]
> I have updated my seedimage to add entries in /etc/hosts, but this doesn't carry across to the OS post install.

Please share more details on this. How do you "update your seedimage" ?


> where I am trying to install RPMs

You shouldn't do this post-install but rather during image build.

**Reply by mightymouse2045** [reply]
I just delete the existing seedimage and create another with kubectl apply -f seedimage.yaml against the rancher cluster:

>apiVersion: elemental.cattle.io/v1beta1
>kind: SeedImage
metadata:
  generation: 3
  name: pch-seedimage
  namespace: fleet-default
  ownerReferences:
    - apiVersion: elemental.cattle.io/v1beta1
      kind: MachineRegistration
      name: vg-registration
      uid: 399bc63c-21c1-42fa-862d-f9e234f2eeda
spec:
  baseImage: registry.suse.com/suse/sle-micro-iso/5.5:2.0.2
  cleanupAfterMinutes: 60
  cloud-config:
    runcmd:
      - echo "1.1.1.1 some.host.com" >> /etc/hosts
  registrationRef:
    name: vg-registration
    namespace: fleet-default


This then generates an updated image which I download and install with that.

Is there another way to build the image and spit out an ISO that I can include installation of extra rpm's as well? I had seen mention of it with elemental toolkit but I have mainly been following guides such as:
https://elemental.docs.rancher.com/customizing#adding-extra-driver-binaries-into-the-iso-example

But if there is a better way can you point me to that?

**Comment by mightymouse2045** [comment]
Ah ok - I get it the docker part didn't sink in when I first read through. So I should create a custom docker build and then use that as the base for the iso image I'm building. Yeah let me try that out.

**Comment by mightymouse2045** [comment]
ok I've progressed to creating the ISO image and it is failing with:

 Failed fetching EFI data: stat /tmp/elemental-iso680850754/rootfs/usr/share/grub2/x86_64-efi/grub.efi: no such file or directory

This happens with the instructions in here and with my custom docker image https://elemental.docs.rancher.com/customizing

**Reply by frelon** [reply]
Hi @mightymouse2045!

Could you share your Dockerfile and the commands used to build the iso?

**Reply by mightymouse2045** [reply]
I have managed to copy the grub files into there and now getting booted and successfully registered into Rancher, however the changes I made to my custom docker image for /etc/hosts haven't come over and I can't work out how to write to fstab in the ISO I have install-hook.yaml with:
name: "Create mount point and update fstab"
stages:
  before-install:
    - commands:
      - mkdir /run/cos/persistent/eVol1
  after-install-chroot:
    - commands:
      - echo "LABEL=eVol1 /usr/local/eVol1  xfs defaults  0 0" >> /etc/fstab
      - 
This is not working to mount my extra disk once I reboot there is only the default items in fstab.

I've also tried with the I yaml file under oem:
name: "Mount LVM volumes"
stages:
  initramfs:
    - name: "Extend fstab to mount LVM logical volumes at boot"
      commands:
      - |
        echo "LABEL=eVol1 /usr/local/eVol1  xfs defaults  0 0" >> /etc/fstab

But neither are working

**Reply by frelon** [reply]
Files directly under `/etc` are going to behave strangely since they are on an ephemeral filesystem. To add lines to `/etc/hosts` we are going to want a cloud-init file in `/oem` that writes to it on every boot.

To place that file in `/oem` during post-install we need another file in the ISO.

This should be possible using the following seedimage:

```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: fire-img
  namespace: fleet-default
spec:
  cleanupAfterMinutes: 0
  baseImage: registry.suse.com/suse/sle-micro-iso/5.5:2.0.2
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: my-nodes
    namespace: fleet-default
  cloud-config:
    users:
      - name: root
        passwd: linux
    runcmd:
      - echo "1.1.1.1 some.host.com" >> /etc/hosts
    write_files:
      - permissions: "0755"
        path: /usr/local/cloud-config/hosts.yaml
        content: |
          name: "Add hosts configuration"
          stages:
            post-install:
              - files:
                - path: /run/cos/oem/90_update-hosts.yaml
                  permissions: 0777
                  content: | 
                    name: "Add hosts configuration"
                    stages:
                      initramfs:
                        - commands:
                          - echo "1.1.1.1 some.host.com" >> /etc/hosts
```

It's not a pretty solution, but it works... We are currently looking into how we can make this process smoother!
