### ISSUE TITLE
Elemental CAPI integrate elemental-toolkit

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental#1061]
The goal of this issue is to enable integration with the elemental-toolkit.

The `elemental` installer should be implemented.
The install and reset fields should also become schema-less data.

The 'unmanaged' installer can be optionally be updated to write these fields in the work dir, under `install.yaml` and `reset.yaml`. 
Up to the users to do anything with them.

```yaml
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: ElementalRegistration
    metadata:
      name: my-registration
      namespace: default
    spec:
      config:
        elemental:
          agent:
            installer: "elemental"
          install:
             anything: goes
          reset:
             anything: goes
```

There should also be a convenient and easy way to locally build a bootable Elemental image, containing the elemental cli, the elemental-agent, and an initial configuration for the agent to register.
