### ISSUE TITLE
Recovery upgrade process

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#1218]
We need way to upgrade recovery image from 5.5 based OS (current stable) to 6.0 based OS (current Dev). The issue is about defining the most appropriate process. Current elemental-toolkit in Dev includes a `--recovery` flag for upgrades that runs an uprade on active system **and** recovery system. I am not convinced this is the best approach though, probably `--recovery` could **only** upgrade recovery image and make the 5.5 to 6.0 upgrade a two step a run (then this requires then some further concept at elemental-operator level).

In addition to the definition of the exact process to upgrade recovery we also need to find a suitable way to include or not the `--recovery` flag during upgrades (probably only on major version bumps? manually pass it as an env variable to the system-upgrade-controller?)

This issue requires exercising the process to digest a simple and suitable approach.

**Comment by anmazzotti** [comment]
I actually like the `--recovery` option and in general to upgrade in one step. I would also like to have an equivalent environment variable.

This would greatly simplify the process for the elemental-agent in the CAPI setting. In that case I would simply expose the option on the registration level, similar as we have `install` and `reset` options, we could add an `upgrade` block where we can add the (upgrade) recovery option, and more eventually.

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ElementalRegistration
metadata:
  name: my-registration
spec:
    elemental:
      install:
        debug: true
        device: "/dev/vda"
      reset:
        resetOem: true
        resetPersistent: true
      upgrade:
        recovery: true
```

It is a bit misleading maybe to call it upgrade, since I guess the same options will be used during downgrades. Just a small detail, maybe we can find a better name.

**Comment by anmazzotti** [comment]
For the current elemental-operator I also think the `--recovery` approach is valid and simpler. Do it in one go.

If we have an environment variable, I believe we could already add it to the ManagedOSVersion Spec medatada and pretty much drive this at a channel level, so we have the option to enforce some recovery upgrade on all users subscribing to our default:

```json
  {
    "metadata": {
      "name": "v1.2.3"
    },
    "spec": {
      "version": "v1.2.3",
      "type": "container",
      "metadata": {
        "upgradeImage": "foo/bar:v1.2.3",
        "upgradeRecovery": true,
      }
    }
  }
```

The flag could be added to both [ContainerImage](https://github.com/rancher/elemental-operator/blob/main/api/v1beta1/managedosversion_types.go#L97) and [ISOImage](https://github.com/rancher/elemental-operator/blob/main/api/v1beta1/managedosversion_types.go#L90) definitions.

**Comment by anmazzotti** [comment]
After some discussion we came to the conclusion that it would be better for the recovery upgrade to work as a standalone operation. 

This should be manually driven by the users. 
One way to trigger it would be to extend the `ManagedOSImage` with a new flag:

```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSImage
metadata:
  name: my-recovery-upgrade
  namespace: fleet-default
spec:
  osImage: my-registry/elemental:1.2.3
  recovery: true
  clusterTargets:
    - clusterName: my-cluster
```

**Comment by anmazzotti** [comment]
Update on the snippet above is that we don't need any changes on the elemental-operator side. 
We can use the already existing `upgradeContainer` field:

```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSImage
metadata:
  name: dev-upgrade
  namespace: fleet-default
spec:
  # Set to the new Elemental version you would like to upgrade to or track the latest tag
  osImage: "172.18.0.2:30000/elemental-os:dev-next"
  clusterTargets:
    - clusterName: volcano
  upgradeContainer:
    envs:
      # Use UPGRADE_RECOVERY_ONLY to upgrade the recovery partition only. (This also has the same effect as FORCE="true")
      - name: UPGRADE_RECOVERY_ONLY
        value: "false"
      # Use UPGRADE_RECOVERY to upgrade both system and recovery partitions. (This also has the same effect as FORCE="true")
      - name: UPGRADE_RECOVERY
        value: "true"
      # Use FORCE to force an upgrade. This is how version downgrades can be performed.
      - name: FORCE
        value: "false"
```
