### ISSUE TITLE
Make snapshotter type easily configurable from the elemental-operator PoV

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#1241]
This is about mapping the snapshotter type to elemental client as a command line flag and environment variable flag and also translate it up to the elemental-operator and elemental-register so it can be easily set in install parameters at registration end point resource.

This will require changes in elemental-toolkit and elementa-operator repositories and, probably, to this repository too in order to change or remove the snapshotter configuration default yaml.

**Comment by anmazzotti** [comment]
Current workaround from @davidcassany 

```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: fire-img
  namespace: fleet-default
spec:
  cloud-config:
    write_files:
    - path: /etc/elemental/config.d/snapshotter.yaml
      content: |
        snapshotter:
          type: btrfs
          max-snaps: 4
  baseImage: registry.opensuse.org/home/dcassany/branches/isv/rancher/elemental/dev/containers/suse/sle-micro-iso/5.5:2.1.0 
  registrationRef:
    name: fire-nodes
    namespace: fleet-default
```
