### ISSUE TITLE
Upgrade FORCE flag leads to endless reboots

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental#1255]
**What steps did you take and what happened:**

Applying a ManagedOSImage using the FORCE flag as described in the [documentation](https://elemental.docs.rancher.com/upgrade)

```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSImage
metadata:
  name: my-upgrade
  namespace: fleet-default
spec:
  # Set to the new Elemental version you would like to upgrade to
  osImage: "registry.suse.com/rancher/elemental-teal/5.3:latest"
  clusterTargets:
    - clusterName: my-cluster
  upgradeContainer:
    envs:
      - name: FORCE
        value: "true"
```

Since the FORCE flag is on, the `suc-upgrade` script does not verify if the current running image already matches the upgrade one. Leading to an endless reboot. 

This should be partially fixed by <https://github.com/rancher/elemental/pull/1226>

However, when comparing the versions, I noticed that the TIMESTAMP is never updated on the running host, always leading to drifts:

```
test-c00616c7-e1e9-422c-a786-9bcd826cd8fd:~ # diff /the-upgrade-pod/etc/os-release /etc/os-release 
13c13
< TIMESTAMP=20240229081330
---
> TIMESTAMP=20240229075058
```

**What did you expect to happen:**

After reboot, the upgrade pod should complete successfully without rebooting the system a second time.

**Environment:**

- Elemental release version (use `cat /etc/os-release`): Latest dev
- Rancher version: 2.8.2
- Kubernetes version (use `kubectl version`): 1.27.10+k3s1
