### ISSUE TITLE
Rancher is not configured correctly by ros-installer

### ISSUE THREAD

**Issue by kleberbaum** [rancher/elemental#127]
https://github.com/rancher-sandbox/os2/blob/304725eef5c0d6a47d53cd48ca899394668fa57a/docs/configuration.md?plain=#L55-L56

## Behavior in v0.1.0 with `ros-installer -config-file`:
```yaml
#cloud-config
hostname: "rancher"

# Assigns these keys to the first user in users or root if there
# is none
ssh_authorized_keys:
  - github:kleberbaum

# Rancherd configuration
rancherd:
  # The Kubernetes version to be installed. This must be a k3s or RKE2 version
  # v1.21 or newer. k3s and RKE2 versions always have a `k3s` or `rke2` in the
  # version string.
  # Valid versions are
  # k3s: curl -sL https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/release-v2.6/data/data.json | jq -r '.k3s.releases[].version'
  # RKE2: curl -sL https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/release-v2.6/data/data.json | jq -r '.rke2.releases[].version'
  kubernetesVersion: v1.22.2+k3s1

  # The Rancher version to be installed or a channel "latest" or "stable"
  rancherVersion: v2.6.0

  # The role of this node.  Every cluster must start with one node as role=cluster-init.
  # After that nodes can be joined using the server role for control-plane nodes and
  # agent role for worker only nodes.  The server/agent terms correspond to the server/agent
  # terms in k3s and RKE2
  role: server

# Any other cloud-init values can be included in this file and will be stored in
# /oem/99_custom.yaml of the installed image
```
```bash
localhost:~ # ros-installer -config-file https://gist.githubusercontent.com/kleberbaum/04ebf13ed040085cdea52fc99d38c970/raw/bb7ca291c4cad7454d9691d4e7748e4db269fff0/rancher.yaml

Configuration
-------------

config_url: https://gist.githubusercontent.com/kleberbaum/04ebf13ed040085cdea52fc99d38c970/raw/bb7ca291c4cad7454d9691d4e7748e4db269fff0/rancher.yaml
device: /dev/vda

Your disk will be formatted and installed with the above configuration.
Continue? [y/N]: y
```
### v0.1.0 with k3s, configured ssh-keys, hostname and rancher:
```bash
rancher:~ # cat /oem/99_custom.yaml
#cloud-config
hostname: rancher
rancherd:
  kubernetesVersion: v1.22.2+k3s1
  rancherVersion: v2.6.0
  role: server
rancheros: {}
ssh_authorized_keys:
- github:kleberbaum
```
```bash
rancher:~ # k3s --version
k3s version v1.22.2+k3s1 (10bca343)
go version go1.16.8
rancher:~ # kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2+k3s1", GitCommit:"10bca343e85180f668522fe252552da20220cb7a", GitTreeState:"clean", BuildDate:"2021-09-23T22:46:18Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2+k3s1", GitCommit:"10bca343e85180f668522fe252552da20220cb7a", GitTreeState:"clean", BuildDate:"2021-09-23T22:46:18Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
https://github.com/rancher-sandbox/os2/blob/304725eef5c0d6a47d53cd48ca899394668fa57a/docs/dashboard.md?plain=#L3-L5
```bash
rancher:~ # rancherd reset-admin
Error: cluster and rancher are not ready. Please try later.: the server could not find the requested resource
Usage:
  rancherd reset-admin [flags]

Flags:
  -h, --help                   help for reset-admin
      --kubeconfig string      Kubeconfig file
      --password string        Password for Rancher login
      --password-file string   Password for Rancher login, from file

FATA[0000] cluster and rancher are not ready. Please try later.: the server could not find the requested resource
```
![image](https://user-images.githubusercontent.com/26285351/168476180-e3dd53af-a11b-4b32-87d7-1a0d7e9dd329.png)

**Comment by kleberbaum** [comment]
## My current workaround

### v0.1.0 with `ros-installer -config-file`:
```yaml
#cloud-config
hostname: "workaround"

# Assigns these keys to the first user in users or root if there
# is none
ssh_authorized_keys:
  - github:kleberbaum

# Rancherd configuration
rancherd:
  # The Kubernetes version to be installed. This must be a k3s or RKE2 version
  # v1.21 or newer. k3s and RKE2 versions always have a `k3s` or `rke2` in the
  # version string.
  # Valid versions are
  # k3s: curl -sL https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/release-v2.6/data/data.json | jq -r '.k3s.releases[].version'
  # RKE2: curl -sL https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/release-v2.6/data/data.json | jq -r '.rke2.releases[].version'
  kubernetesVersion: v1.22.2+k3s1

  # The Rancher version to be installed or a channel "latest" or "stable"
  rancherVersion: v2.6.0

  # The role of this node.  Every cluster must start with one node as role=cluster-init.
  # After that nodes can be joined using the server role for control-plane nodes and
  # agent role for worker only nodes.  The server/agent terms correspond to the server/agent
  # terms in k3s and RKE2
  role: server

# Write setup script
write_files:
- content: |
    #!/bin/bash
    # Install cert-manager
    # Create a namespace
    kubectl create namespace cert-manager
    # Install cert-manager CRDs
    kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.1/cert-manager.crds.yaml

    # Add the Jetstack Helm repository
    helm repo add jetstack https://charts.jetstack.io

    # Update your local Helm chart repository cache
    helm repo update

    # Install the cert-manager Helm chart
    helm install cert-manager jetstack/cert-manager \
      --namespace cert-manager \
      --create-namespace \
      --version v1.5.1
    # Verify rollout
    kubectl -n cert-manager rollout status deploy/cert-manager-webhook
    kubectl -n cert-manager rollout status deploy/cert-manager
    
    # Install Rancher
    # Add rancher-latest repo
    helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
    # Update the repo
    helm repo update
    # Setup Namespace
    kubectl create namespace cattle-system
    # Install Rancher using Helm
    helm install rancher rancher-stable/rancher \
      --namespace cattle-system \
      --set hostname=rancher.test.net \
      --set bootstrapPassword=ros
    # Verify rancher deployed successfully
    kubectl -n cattle-system rollout status deploy/rancher
  path: /usr/local/bin/cloud-init-workaround
  permissions: "0755"
  owner: "root"

# Any other cloud-init values can be included in this file and will be stored in
# /oem/99_custom.yaml of the installed image
```

### At the moment I am executing my workaround script manually after installation
```bash
workaround:~ # cloud-init-workaround
```

- Is there a way I could run my script automatically?
- What is the best way to install helm charts automatically or to achieve something similar at the moment?
