### ISSUE TITLE
Testing SELlinux images in the CI

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#1403]
Devoted worflows for K3S should be set independently of any other test. RKE2 provisioning is not ready yet.

We could either create a SELinux channel and then use this channel to pull the SELinux images or either manually the devoted ManagedOSVersions for the SELinux images.

`suse/sl-micro/k3s-selinux-os-container`
`suse/sl-micro/k3s-selinux-iso-image`

In additiont the cluster should be set to make use of SELinux, so containerd is properly configured:
```yaml
kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: volcano
  namespace: fleet-default
spec:
  rkeConfig:
    machineGlobalConfig:
      selinux: true
```
