### ISSUE TITLE
Support Yip syntax and cloud-init syntax all together

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#1437]
**Describe the solution you'd like:**
Use Yip and/or cloud-init syntax in any cloud-config field.

**Anything else you would like to add:**
 Imagine an example such as:
 
 ```yaml
 stages:
  network:
  - command:
    - wget https://example.com/my-fancy-file

write_files:
- path: /etc/pki/trust/anchors/exmaple.com-certificate.pem
  permission: 0444
  content: "my certificate"
 ```

**Environment:**

- Elemental release version (use `cat /etc/os-release`):
- Rancher version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
