### ISSUE TITLE
ci: check that machine inventory annotations are up-to-date after upgrade/reboot

### ISSUE THREAD

**Issue by juadk** [rancher/elemental#1530]
Full story [here](https://github.com/rancher/elemental-operator/issues/811)

The values are taken from `/etc/os-release`
There is also the ip address to check. 

Test might be done either on CLI or UI.

Example:
```
  annotations:
    elemental.cattle.io/auth: tpm
    elemental.cattle.io/os.cpe-name: cpe:/o:suse:sl-micro:6.0
    elemental.cattle.io/os.id: sl-micro
    elemental.cattle.io/os.image: >-
      registry.opensuse.org/isv/rancher/elemental/staging/containers/suse/sl-micro/6.0/baremetal-os-container:2.1.2-10.6
    elemental.cattle.io/os.name: SL-Micro
    elemental.cattle.io/os.pretty-name: SUSE Linux Micro 6.0
    elemental.cattle.io/os.version: '6.0'
    elemental.cattle.io/os.version-id: '6.0'
    elemental.cattle.io/reg-version: 1.6.3
    elemental.cattle.io/registration-ip: 192.168.1.158
    elemental.cattle.io/resettable: 'true'
  creationTimestamp: '2024-08-08T12:36:14Z'
```
