### ISSUE TITLE
ci: try to reduce the number of inputs entries in CI workflows

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#1564]
Instead of using input entries like this:
```yaml
jobs:
  cli:
    with:
      k8s_downstream_version: ${{ matrix.k8s_downstream_version }}
      k8s_upstream_version: ${{ matrix.k8s_upstream_version }}
      qase_run_id: ${{ github.event_name == 'schedule' && 'auto' || inputs.qase_run_id }}
      rancher_version: ${{ matrix.rancher_version }}
      reset: ${{ matrix.reset }}
      sequential: ${{ matrix.sequential }}
      test_type: cli
      zone: us-central1-c
```
We could try to use something like this:
```yaml
jobs:
  cli:
    with:
      k8s_downstream_version: ${{ matrix.k8s_downstream_version }}
      k8s_upstream_version: ${{ matrix.k8s_upstream_version }}
      qase_run_id: ${{ github.event_name == 'schedule' && 'auto' || inputs.qase_run_id }}
      rancher_version: ${{ matrix.rancher_version }}
      test_to_run: "reset sequential cli"
      zone: us-central1-c
```
To reduce the number of inputs.

This issue is here to do a PoC based on this idea and see what is the better/easier solution.
