### ISSUE TITLE
Activate serial console

### ISSUE THREAD

**Issue by philippebi** [rancher/elemental#1629]
The serial console is currently not configured on Elemental OS. Could you please add the kernel extra argument 'console=ttyS0,115200' by default to make it work?

**Comment by ldevulder** [comment]
As we quickly discussed on Slack, I think it is not possible to have something that will work on all type of hardware. As a former sysadmin I can say that on x86 I saw baremetal with remote console configured on `ttyS0`, some with `ttyS1`, with also mix of speed configuration: 9600, 19200 or 115200. So there's no real "default" configuration.

And I don't know if it's still the case but the IPMI specification set the default baud rate for BMC at 19200 and sometimes it is not configurable (it was the case for some IBM servers).

Just my 2 cent, regarding my previous experiences ;-)

But in the KVM image/iso maybe it could be defined, as this doesn't follow IPMI rules, so easier in that case.

**Comment by kkaempf** [comment]
See also https://github.com/rancher/elemental-toolkit/issues/1773 😉

**Comment by philippebi** [comment]
Note that as a workaround, the following works:

```
config:
  cloud-config:
    stages:
      after-install-chroot:
      - name: "Set serial console"
        commands:
          - grub2-editenv /oem/grubenv set extra_cmdline="console=ttyS0,115200"
```
