### ISSUE TITLE
OS update is never triggered

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#1676]
**What steps did you take and what happened:**
Create a new OS channel pointing to newer image versions, create an update group to upgrade the OS on the nodes.

**What did you expect to happen:**
OS image on the nodes updated from SLEMicro 6.0 to 6.1.

**Anything else you would like to add:**
Find elemental-operator logs: [upgrade.log](https://github.com/user-attachments/files/18750970/upgrade.log).

**Environment:**

- Elemental release version (use `cat /etc/os-release`): 
```
NAME="SL-Micro"
VERSION="6.0"
VERSION_ID="6.0"
PRETTY_NAME="SUSE Linux Micro 6.0"
ID="sl-micro"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sl-micro:6.0"
HOME_URL="https://www.suse.com/products/micro/"
DOCUMENTATION_URL="https://documentation.suse.com/sl-micro/6.0/"
IMAGE_REPO="registry.suse.com/suse/sl-micro/6.0/baremetal-os-container"
IMAGE_TAG="2.1.3-4.7"
IMAGE="registry.suse.com/suse/sl-micro/6.0/baremetal-os-container:2.1.3-4.7"
TIMESTAMP=20241107104849
GRUB_ENTRY_NAME="SUSE Linux Micro"
```
- Rancher version: Prime v2.10.2
- Kubernetes version (use `kubectl version`): v1.30.6+k3s1 for Rancher Manager and v1.30.8+k3s1 for the Elemental cluster
- Cloud provider or hardware configuration: Virtual Machines.

**How to reproduce the issue:**
- Deploy Rancher Manager Stable or Prime version
- Create a simple Elemental cluster (1 node is enough) with Stable version (operator v1.6.5, OS channel v6.0)
- Add the Staging OS channel:
```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersionChannel
metadata:
  name: sl-micro-6.1-baremetal-channel
  namespace: fleet-default
spec:
  options:
    image: registry.opensuse.org/isv/rancher/elemental/staging/containers/rancher/elemental-channel/sl-micro:6.1-baremetal
  syncInterval: 1h
  type: custom
```
- Create an update group:
```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSImage
metadata:
  name: upgrade-os-to-6.1
  namespace: fleet-default
spec:
  clusterTargets:
    - clusterName: test-cluster
  managedOSVersionName: baremetal-v2.2.0-3.7-os
```
- All looks good but the update is never triggered

**Comment by ldevulder** [comment]
I tested with `osImage` option instead of `managedOSVersionName` and it worked **BUT ONLY** with `dev` instead of `staging`:
```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSImage
metadata:
  name: upgrade-os
  namespace: fleet-default
spec:
  clusterTargets:
    - clusterName: test-cluster
  osImage: registry.opensuse.org/isv/rancher/elemental/dev/containers/suse/sl-micro/6.1/baremetal-os-container:latest
```

I checked and `staging` is available on `registry.opensuse.org`, like `dev`.
