### ISSUE TITLE
Wrong machineName during reset

### ISSUE THREAD

**Issue by max06** [rancher/elemental#1689]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Resetting an elemental machine (causing reboot to recovery+reset) re-registers the machine with `localhost.localdomain` instead of the generated hostname. This causes severe issues when resetting more than one machine.

**What did you expect to happen:**
The hostname should either not change, or be regenerated following the usual schema.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: cluster-002
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
      - name: root
        passwd: root
    elemental:
      install:
        device-selector:
        - key: Name
          operator: In
          values:
          - /dev/sda
        reboot: true
        snapshotter:
          type: btrfs
      registration:
        auth: tpm
        emulate-tpm: true
        emulated-tpm-seed: -1
      reset:
        enabled: true
        reboot: true
        reset-oem: true
        reset-persistent: true
  machineInventoryLabels:
    elemental.cattle.io/CpuTotalCores: ${System Data/CPU/Total Cores}
    elemental.cattle.io/CpuTotalThreads: ${System Data/CPU/Total Threads}
    elemental.cattle.io/NumDisks: ${System Data/Block Devices/Number Devices}
    elemental.cattle.io/TotalMemoryBytes: ${System Data/Memory/Total Physical Bytes}
    elemental.cattle.io/edge: cluster-002
    elemental.cattle.io/machineUUID: ${System Information/UUID}
    elemental.cattle.io/manufacturer: ${System Information/Manufacturer}
    elemental.cattle.io/productName: ${System Information/Product Name}
    elemental.cattle.io/serialNumber: ${System Information/Serial Number}
  machineName: ${System Data/Runtime/Hostname}.cluster-002
``` 

**Environment:**

- Elemental release version (use `cat /etc/os-release`): 2.1.3-4.17
- Rancher version: v2.10.3
- Kubernetes version (use `kubectl version`): v1.31.5+rke2r1
- Cloud provider or hardware configuration:

    Hardware, no TPM, simple dhcp with no hostnames

---

Additional question: Should I disable `reset-oem` when using emulated tpm to avoid loosing the generated tpm hash during reset?
