### ISSUE TITLE
Add Rancher RBAC on operator installation

### ISSUE THREAD

**Issue by agracey** [rancher/elemental#332]
As part of https://github.com/rancher/elemental/issues/288, we should add an RBAC role that allow the correct access to the CRDs.

These are controlled in the globalroles.management.cattle.io CRD. 

Docs for custom roles through the UI but the yaml looks basically the same as a standard k8s role:
https://docs.ranchermanager.rancher.io/how-to-guides/advanced-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/custom-roles

**Comment by fgiudici** [comment]
This is a subtask of #368

**Comment by mjura** [comment]
@agracey Just wondering what should be done for this task, because currently we have RBAC for elemental-operator https://github.com/rancher/elemental-operator/blob/main/chart/templates/rbac.yaml

Which `apiGroup` is missing there ?

**Comment by mjura** [comment]
We had call with @agracey where it was specified that we have to create following object during elemental-operator helm installation

```
apiVersion: management.cattle.io/v3
builtin: true
description: ""
displayName: Manage Catalogs
kind: GlobalRole
metadata:
  annotations:
    authz.management.cattle.io/cr-name: cattle-globalrole-catalogs-manage
    lifecycle.cattle.io/create.mgmt-auth-gr-controller: "true"
  finalizers:
  - controller.cattle.io/mgmt-auth-gr-controller
  labels:
    authz.management.cattle.io/bootstrapping: default-globalrole
    cattle.io/creator: norman
  name: catalogs-manage
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - catalogs
  - templates
  - templateversions
  verbs:
  - '*'
```
