### ISSUE TITLE
usb drive with iso seems to be single use

### ISSUE THREAD

**Issue by agracey** [rancher/elemental#372]
**What steps did you take and what happened:**
When I burn an iso to a USB drive then boot a NUC with it something seems to happen and I can't boot a second time without burning again. 

**What did you expect to happen:**
I would expect that the USB can be used many times without issue. 

**Anything else you would like to add:**
This seems to be new behavior in 0.6.0 or the newer Teal image.

NUCs use /dev/nvme0n1 

Machine Registration:
```
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: homelab
  namespace: fleet-default
spec:
  config:
    cloud-config:
      registration: {}
      users:
      - name: root
        passwd: root
    elemental:
      install:
        device: /dev/nvme0n1
        eject-cd: true
        poweroff: true
      registration: {}
      system-agent: {}
  machineInventoryLabels:
    registration: homelab
    serialNumber: ${Base Board Information/Serial Number}
  machineName: homelab-${Base Board Information/Serial Number}
```

I will keep this iso around in case anyone wants to shoulder surf to diagnose

**Environment:**

- Elemental release version (use `cat /etc/os-release`): 0.6.0
- Rancher version: 2.6.7
- Kubernetes version (use `kubectl version`): 1.22.x? (I need to upgrade again...)
- Cloud provider or hardware configuration: Digital Ocean for upstream cluster, Intel NUCs for downstream machines
