### ISSUE TITLE
SSH `github`/`gitlab` auth not working after install

### ISSUE THREAD

**Issue by jsundqvist** [rancher/elemental#55]
Using the following config.yaml I can `ssh` into the machine _during_ the install, but not after. (It asks for passwd). Why?

```
#cloud-config
rancherd:
  role: cluster-init

# See https://rancher-sandbox.github.io/cos-toolkit-docs/docs/reference/cloud_init/ for a full syntax reference
stages:
  initramfs:
  - users:
      jsundqvist:
  network:
  - authorized_keys:
      jsundqvist:
      - github:jsundqvist

```
EDIT: Same for `gitlab`
