### ISSUE TITLE
Unable to reset the Rancher admin password

### ISSUE THREAD

**Issue by divyashukla25** [rancher/elemental#592]
Could you please tell me how we can change the Rancher password in Elemental OS?

**Comment by kkaempf** [comment]
You don't. 😉 
Elemental is not supposed to make changes to the configuration of a deployed node.
Instead, you change (the root password in) the `machineRegistry` and redeploy.

**Comment by Itxaka** [comment]
Link to rancher docs: https://ranchermanager.docs.rancher.com/faq/technical-items#how-can-i-reset-the-administrator-password

Nothing to do with Elemental OS as we dont install rancher ourselves :)

**Comment by divyashukla25** [comment]
@Itxaka I already tried with this link, but it's reset the password and provided a random one. I want to change it with some specific one. 
I'm using an Elemental airgap OS and Rancher is pre-installed & have an admin.yaml file which store the password in encrypted form, and this is the same password which I'm using for the login. I guess if we change the password in this file it'll work. But I don't know which Encryption algorithm it is using. I tried few but no luck. 

File - /usr/local/.state/var-lib-rancher.bind/k3s/server/manifests/iqem/rancher-settings/admin.yaml
```
---
apiVersion: management.cattle.io/v3
kind: User
metadata:
  name: admin
  labels:
    created-by: test
    authz.management.cattle.io/bootstrapping: admin-user
username: admin
password: "$2a$12$.DyyasORiWTxwooS2oNUX.kEchlw99v/2EsW.v1.A0.z.XQ1HEx/K"
displayName: "Default Admin"
mustChangePassword: false
enabled: true
```

It would be great if you could tell me which Encryption algorithm it's using?
