### ISSUE TITLE
Create ugrade channels for elemental-teal images

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#649]
We need to build a list of available OS images (most likely a JSON) that is compliant with ManagedOSVersionChannel and ManagedOSVersion crds and find a way to distribute it.

I'd suggest to start by creating a dump container image containing such a json and use it for upgrades validation.

IMHO we should have such an image in `Staging` including the current staging tag and the latest version from stable and an equivalent image in `Dev` including the latest version from staging and current dev.

Ideally the outcome of this card are some automated images synched in OBS including the mentioned JSON.

I am also wondering we should consider publishing multiple images in Stable are in OBS to mimic IBS and fill the gap until publishing is ready there. I am not completely sure the effort is worth...

**Comment by agracey** [comment]
FWIW, this is the ManagedOSVersionChannel spec that I've been demoing with. It seems to work?

```
spec:
  options:
    args:
    - -c
    - |
      curl -X GET https://registry.opensuse.org/v2/isv/rancher/elemental/teal53/15.4/rancher/elemental-teal/5.3/tags/list | jq '[.tags[] | { metadata: { name: . }, spec: { version: . , type: "container", metadata: { upgradeImage: ["isv/rancher/elemental/teal53/15.4/rancher/elemental-teal/5.3:", .] |join("") }}}]' > /data/output
    command:
    - bash
    envs:
    - name: REGISTRY
      value: registry.opensuse.org
    - name: IMAGE_NAME
      value: isv/rancher/elemental/teal53/15.4/rancher/elemental-teal/5.3
    image: registry.opensuse.org/home/atgracey/containerfile/jq:latest
  type: custom
```

**Comment by davidcassany** [comment]
> FWIW, this is the ManagedOSVersionChannel spec that I've been demoing with

Interesting approach, thanks

**Comment by davidcassany** [comment]
All right I finally created an image including an static version of such a JSON. It is in OBS in `Dev` as  `dev-channel-image`. This image produces managed OS versions for `dev`, `staging` and  `stable`. It can be simply included into elemental with

```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersionChannel
metadata:
  name: elemental-test-channel
  namespace: fleet-default
spec:
  options:
    image: registry.opensuse.org/isv/rancher/elemental/dev/teal53/15.4/rancher/elemental-teal-channel/5.3:latest
  type: custom
```

Then the created ManagedOSVersions can be used for update groups as:

```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSImage
metadata:
  name:  my-upgrade
  namespace: fleet-default
spec:
  managedOSVersionName: dev
  clusterTargets:
    - clusterName: <mycluster>
```

I did a trial upgrading from stable to dev and it was functional. Then I also created a new upgrade to switch to staging and it worked fine.

I'd say this is can be a good way to test teal upgrades.

**Comment by davidcassany** [comment]
Closing the issue since this is already available for its use in https://build.opensuse.org/package/show/isv:Rancher:Elemental:Dev:Teal53/dev-channel-image

The channel can be added as 
```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersionChannel
metadata:
  name: elemental-test-channel
  namespace: fleet-default
spec:
  options:
    image: registry.opensuse.org/isv/rancher/elemental/dev/teal53/15.4/rancher/elemental-teal-channel/5.3:latest
  type: custom
```
