### ISSUE TITLE
Cannot set a custom registries.yaml on downstream clusters

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental#717]
**What steps did you take and what happened:**

I created a registration endpoint with:

```yaml
spec:
  config:
    cloud-config:
      write_files:
      - path: /etc/elemental/ca_certs/custom.pem
        owner: root:root
        permissions: '0644'
        content: |
          -----BEGIN CERTIFICATE-----
          MIIG6DCCBNCgAwIBAgIBATANBgkqhkiG9w0BAQsFADCBqDELMAkGA1UEBhMCREUx
          ...
          -----END CERTIFICATE-----
      - path: /etc/rancher/k3s/registries.yaml
        owner: root:root
        permissions: '0644'
        content: |
          configs:
            registry.suse.de:
              tls:
                ca_file: /etc/elemental/ca_certs/custom.pem
```

And a OS provisioning time (`elemental install`) the files are created as expected during boot. However as soon as the k3s or rke2 provisioning kicks in the `/etc/rancher/k3s/registries.yaml` is overwritten by an empty one. 

If I rewrite again the file and restart the service the file is kept as expected. However it gets lost in every reboot.
 
**What did you expect to happen:**
After provisioning k3s or rke2 have a custom `resgistries.yaml` setup.

**Anything else you would like to add:**
I have been facing that trying to set downstream clusters to pull images from `registry.suse.de`, which is not signed with a known CA.

**Environment:**

- Elemental release version (use `cat /etc/os-release`): stable, staging and dev
- Rancher version: 2.7.1
- Kubernetes version (use `kubectl version`): 1.24.10+k3s1
