### ISSUE TITLE
e2e: test cloud-init setup for the SeedImage

### ISSUE THREAD

**Issue by juadk** [rancher/elemental#764]
Follow up of https://github.com/rancher/elemental-operator/issues/378

During the planning meeting, we agreed to test it manually before the next release and do the automation later.
I will see if I create another issue or not.

- [x] Manual test before next release
- [ ] Automation

**Comment by juadk** [comment]
What I do to manually test cloud-init for the SeedImage:

I apply this file:
```
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: myseedimage
  namespace: fleet-default 
spec:
  baseImage: https://download.opensuse.org/repositories/isv:/Rancher:/Elemental:/Dev:/Teal53/media/iso/elemental-teal.x86_64.iso
  cloud-config:
    write_files:
    - content: |
        # My new /etc/testcloudconfig file
        # You should be able to see me :-)
      path: /etc/testcloudconfig
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: machine-registration
    namespace: fleet-default
```
it built my ISO and I booted a machine from it:


![Image](https://user-images.githubusercontent.com/6025636/228287728-1b47ffc7-ce1c-4fb9-b6a5-ead66c97646c.png)
