### ISSUE TITLE
ci: modify CheckClusterState function to use proper status

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental#965]
Status in `kubectl -n fleet-default get cluster cluster-rke2 -o yaml` shows all we need:
```yaml
[...]
status:
  agentDeployed: true
  clientSecretName: cluster-rke2-kubeconfig
  clusterName: c-m-68tzcftn
  conditions:
 - lastUpdateTime: "2023-08-21T12:34:20Z"
   status: "False"
   type: Reconciling
 - lastUpdateTime: "2023-08-21T12:21:28Z"
   status: "False"
   type: Stalled
 - lastUpdateTime: "2023-08-21T12:37:14Z"
   status: "True"
   type: Created
 - lastUpdateTime: "2023-08-21T12:37:44Z"
    status: "True"
    type: Updated
 - lastUpdateTime: "2023-08-21T12:37:44Z"
   status: "True"
   type: Provisioned
 - lastUpdateTime: "2023-08-21T12:37:44Z"
   status: "True"
   type: Ready
 - lastUpdateTime: "2023-08-21T12:34:13Z"
   status: "True"
   type: AgentDeployed
 - lastUpdateTime: "2023-08-21T12:34:20Z"
   status: "True"
   type: Waiting
```

So it could be useful to use these states and code something better in `CheckClusterState` function.
