### ISSUE TITLE
Elemental CAPI components shipping

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental#990]
This issue serves to design and implement a way for the Elemental CAPI provider to ship the correct k8s components to hosts. 

As a context, with CAPI we can have several [bootstrap providers](https://cluster-api.sigs.k8s.io/reference/providers#bootstrap) generating cloud-init configs to bootstrap nodes.  

Note however that the bootstrap providers will not issue any instructions on how to download and install needed binaries, or which version of those binaries should be installed, or how to restart specific services after the cloud-init config is applied. 

For example, when using the Kubeadm provider, the kubeadm binary and all other dependencies is expected to be already installed on the host machines. 

This implies that if we want to support multiple providers, for example kubeadm, rke2, and k3s, we will need to have all these dependencies included in the Elemental image, or... we can find an alternative approach. 

An alternative approach would be to publish bundles with the needed dependencies as an additional layer to the OS image. 
The end user can potentially configure (and upgrade?) these bundles by defining them at the `ElementalMachineTemplate` level so that it should be propagated to the underlying `ElementalMachines`.  For example:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ElementalMachineTemplate
metadata:
  name: elemental-cluster-md-0
  namespace: default
spec:
  template:
    spec:
      componentsBundle: registry.suse.com/rancher/elemental/bundles/rke2:v1.26.7+rke2r1
```

This will have the benefit that components can be customized and are also decoupled from the base Elemental image, so that it will be possible to update them independently. 
The drawback is to maintain these bundles and make sure we are up to date with major versions of components and security vulnerabilities. 

Open questions:
- How should bundling work? Should an installation script be included in the image? How should the agent use/unpack/install the bundle?
- How will be possible to create custom bundles to be easily used in the same way? 
- How will bundles support different distributions? What if my base Elemental image is built on top of RHEL or Debian for example? 
- How will bundle upgrade work within the context of [CAPI upgrades](https://cluster-api.sigs.k8s.io/tasks/upgrading-clusters.html)?
